version: '3.1'

services:
    nginx:
        image: nginx:1.15
        container_name: nginx
        volumes:
            - ../:/var/www
            - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        networks:
            - my-network
        depends_on:
            - server
            - client
    client:
        build:
            context: ../client
            dockerfile: Dockerfile
        container_name: client
        command: npm start
        volumes:
            - ../client:/usr/app
            - /usr/app/node_modules
        networks:
            my-network:
                aliases:
                    - client
        command: npm start
        stdin_open: true
        ports:
            - "3000:3000"
    server:
        build:
            context: ../
            dockerfile: server/Dockerfile
        container_name: server
        command: gunicorn --bind 0.0.0.0:5000 --workers 4 --pythonpath /var/www/ "server.app:app"
        volumes:
            - ../server:/var/www/server
        networks:
            my-network:
                aliases:
                    - server
        expose:
            - 5000
        ports:
            - "5000:5000"
        depends_on:
            - postgres
    postgres:
        image: postgres:15
        expose:
          - "5432"
        ports:
          - "5433:5432"
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=42687193
        volumes:
          - postgres:/var/lib/postgres/data:rw
    pgadmin:
        image: dpage/pgadmin4:4.23
        environment:
          - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
          - PGADMIN_DEFAULT_PASSWORD=password
          - PGADMIN_LISTEN_PORT=80
        ports:
          - 15432:80/tcp
        volumes:
          - pgadmin:/var/lib/pgadmin
        depends_on:
          - postgres
volumes:
    postgres:
    pgadmin:
networks:
    my-network: